# Site settings
url: "https://bitcoindubai.ae"
author: "bzero"
baseurl: ""
deploy_version: "55c6a87"

exchange: "bitex"
exchange_logo: "bitex"
exchange_toolbar_logo: "bitex_inverse"

custom_css: "bitex"

twitter_widget_id: "717629137503043584"
twitter_widget_name: "bitexstatus"
twitter_widget_theme: "light"
twitter_widget_link_color: "#E8683E"

default_country_code: "BR"
blinktrade_broker_id: 5

blinktrade_backend_api: "bitcoindubai.ae"
google_analytics_id: "UA-57478613-1"
zendesk_host: "bitex.zendesk.com"
custom_faq: "https://bitex.zendesk.com/hc/pt-br"

trading_view: 'bitex:BTCBRL'

# Build settings
markdown: kramdown

remittance_box: "{
    'BRL':[ ['BitFinexUSD',        'USD', 'BITFINEX_BTCUSD_BEST_BID / 100000000', 'BITFINEX_BTCUSD_BEST_ASK / 100000000'  ],
            ['Dólar Bitcoin',      'BRL', 'BLINK_BTCBRL_BEST_BID /  BITFINEX_BTCUSD_BEST_ASK', 'BLINK_BTCBRL_BEST_ASK /  BITFINEX_BTCUSD_BEST_BID'  ],
            ['Dólar Turismo',      'BRL', 'UOL_USDBRT_BEST_BID / 100000000', 'UOL_USDBRT_BEST_ASK / 100000000' ],
            ['Dólar Comercial',    'BRL', 'UOL_USDBRL_BEST_BID / 100000000', 'UOL_USDBRL_BEST_ASK / 100000000' ] ],
    'USD':[ ['BitFinexUSD',        'USD', 'BITFINEX_BTCUSD_BEST_BID / 100000000', 'BITFINEX_BTCUSD_BEST_ASK / 100000000'  ],
            ['BitStampUSD',        'USD', 'BITSTAMP_BTCUSD_BEST_BID / 100000000', 'BITSTAMP_BTCUSD_BEST_ASK / 100000000'  ],
            ['KrakenUSD',          'USD', 'KRAKEN_BTCUSD_BEST_BID / 100000000', 'KRAKEN_BTCUSD_BEST_ASK / 100000000'  ],
            ['itBitUSD',           'USD', 'ITBIT_BTCUSD_BEST_BID / 100000000', 'ITBIT_BTCUSD_BEST_ASK / 100000000'  ] ]
    }"

symbol: "BTCUSD"

languages: ["en_US", "pt_BR"]

video : 'true'
navbar: 'navbar-default'
phrases: [phrase1, phrase2, phrase4]

exclude:     [ "jsdev", "LICENSE", "README.md", "config.rb", "deploy.sh", "build_javascript.sh", "node_modules", "gulpfile.js", "themes/ander" ]
source:      .
destination: ./_site
plugins_dir:     ./_plugins
gems: [jekyll-paginate, jekyll-multiple-languages-plugin]
paginate:    5
paginate_path: "post/page:num"
permalink:     /post/:title/
blog: http://www.bitex.com.br/blog/
facebook: https://www.facebook.com/bitexcoin
twitter: https://twitter.com/bitexcoin
gplus: https://plus.google.com/+bitexBrasil/posts
youtube: https://www.youtube.com/playlist?list=PL6c8tfdY-CX_VTwU1B9XbzWtIQjY__vrW

sass:
  sass_dir: assets/themes/coinage/sass
  style: :compressed
