version: '2'

services:
        match:
                build:
                        context: .
                        dockerfile: match/Dockerfile
                volumes: 
                        - /opt/bitex:/opt/bitex
        ws_gw:
                build:
                        context: .
                        dockerfile: ws_gateway/Dockerfile
                volumes: 
                        - /opt/bitex:/opt/bitex

        frontend:
                build: ./frontend
                command: echo "Compile-only container"
                volumes: 
                        - /opt/bitex/static:/opt/bitex/static

        ssl:
                build:
                        context: .
                        dockerfile: ssl/Dockerfile
                volumes: 
                        - /opt/bitex:/opt/bitex

        nginx:
                restart: always
                build: ./nginx
                volumes: 
                        - /opt/bitex:/opt/bitex
                depends_on:
                        - ssl
                ports:
                        - "80:80"
                        - "443:443"
