version: '2'

services:
    match:
        build:
            context: .
            dockerfile: match/Dockerfile
        volumes: 
            - bitex-data:/opt/bitex
    ws_gw:
        build:
            context: .
            dockerfile: ws_gateway/Dockerfile
        volumes: 
            - bitex-data:/opt/bitex
        ports:
            - "8445:8445"
        depends_on:
            - match


    nginx:
        build: ./nginx
        volumes: 
            - bitex-data:/opt/bitex
        depends_on:
            - ws_gw
        ports:
            - "80:80"
            - "443:443"
    bitcoind:
        build:
            context: .
            dockerfile: bitcoind/Dockerfile
        depends_on:
            - nginx
        volumes: 
            - bitcoind-data:/bitcoin
        ports:
            - "8332:8332"
            - "8333:8333"
            - "18332:18332"
            - "18333:18333"
        environment: 
            - TESTNET=1
            - DISABLEWALLET=0
            - PRINTTOCONSOLE=1

    receiver:
        build:
            context: .
            dockerfile: receiver/Dockerfile
        volumes: 
            - bitex-data:/opt/bitex
        depends_on:
            - bitcoind

volumes:
    bitcoind-data:
    bitex-data:
