version: '2'

services:
        match:
                build:
                        context: .
                        dockerfile: match/Dockerfile
                volumes: 
                        - /opt/bitex:/opt/bitex
                        - /opt/bitex/db:/opt/bitex/db
                        - /opt/bitex/logs:/opt/bitex/logs
                depends_on:
                        - frontend
        ws_gw:
                build:
                        context: .
                        dockerfile: ws_gateway/Dockerfile
                volumes: 
                        - /opt/bitex:/opt/bitex
                ports:
                        - "8445:8445"
                depends_on:
                        - match

        frontend:
                build:
                        context: .
                        dockerfile: frontend/Dockerfile
                volumes: 
                        - /opt/bitex/static:/opt/bitex/static

        nginx:
                restart: always
                build: ./nginx
                volumes: 
                        - /opt/bitex/static:/opt/bitex/static
                        - /opt/bitex/ssl:/opt/bitex/ssl
                depends_on:
                        - ws_gw
                ports:
                        - "80:80"
                        - "443:443"
